### ISSUE TITLE
when i saveToHuaWeiWallet,it return [internal error]

### ISSUE THREAD

**Issue by yueyue10** [HMS-Core/hms-wallet-clientdemo-android#1]
When i saveToHuaWeiWallet()【add by wallet kit sdk】，it always return 【internal error】。
这是哪里的问题啊？
Contants 里面的【PRIVATE_KEY_DEBUG】和【SESSION_KEY_PUBLIC】这两个值在哪里生成的呢？

**Comment by Mike-mei** [comment]
【PRIVATE_KEY_DEBUG】的生成方法可参考[文档](https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides-V5/preparations-secret-0000001050158422-V5#ZH-CN_TOPIC_0000001050158422__section1785513511827)
【SESSION_KEY_PUBLIC】的值和Constant.java保持一致，不需要修改
